language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
script:
    - yarn run build
    - yarn run build:storybook
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: build
    github_token: $GITHUB_TOKEN
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: "nikolay.vasilyev@nexign.com"
    api_key: $NPM_TOKEN
    tag: latest
    on:
      branch: master
