language: node_js
node_js:
- node
script:
- yarn run build
- yarn run build:storybook
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: deploy
  on:
    branch: master
    node_js: "node"
